In [1]:
import numpy as np
import cv2 as cv
import glob

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('left[0-9][0-9].jpg')
print(images)

for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
 
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (9,6), None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

    print(fname + " OK")
    corners2 = cv.cornerSubPix(gray, corners, (11, 11), (-1,-1), criteria)
    imgpoints.append(corners2)
 
    # Draw and display the corners
    cv.drawChessboardCorners(img, (9,6), corners2, ret)
    cv.imshow('img', img)
    cv.waitKey(1500)
 
cv.destroyAllWindows()

['left01.jpg', 'left02.jpg', 'left03.jpg', 'left04.jpg', 'left05.jpg', 'left06.jpg', 'left07.jpg', 'left08.jpg', 'left09.jpg', 'left11.jpg', 'left12.jpg', 'left13.jpg', 'left14.jpg']
left01.jpg OK
left02.jpg OK
left03.jpg OK
left04.jpg OK
left05.jpg OK
left06.jpg OK
left07.jpg OK
left08.jpg OK
left09.jpg OK
left11.jpg OK
left12.jpg OK
left13.jpg OK
left14.jpg OK


In [5]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [7]:
print(ret, mtx, dist, rvecs, tvecs)

0.40869477031110363 [[536.07345238   0.         342.37046831]
 [  0.         536.01636205 235.53687171]
 [  0.           0.           1.        ]] [[-0.26509041 -0.04674209  0.00183302 -0.00031469  0.252312  ]] (array([[0.16853574],
       [0.27575303],
       [0.01346808]]), array([[ 0.41306799],
       [ 0.64934487],
       [-1.33719473]]), array([[-0.27697515],
       [ 0.18689084],
       [ 0.35483186]]), array([[-0.11082293],
       [ 0.23974749],
       [-0.0021351 ]]), array([[-0.29188245],
       [ 0.42829916],
       [ 1.31269861]]), array([[0.40772928],
       [0.30384779],
       [1.64906548]]), array([[0.17947256],
       [0.34574754],
       [1.86847039]]), array([[-0.09096664],
       [ 0.47965881],
       [ 1.7533841 ]]), array([[ 0.20290341],
       [-0.42414241],
       [ 0.1324557 ]]), array([[-0.41926886],
       [-0.49992924],
       [ 1.33554719]]), array([[-0.23849925],
       [ 0.34777535],
       [ 1.53073676]]), array([[ 0.46301579],
       [-0.2830716 ],
     

In [43]:
img = cv.imread('left12.jpg')
h, w = img.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

In [45]:
# undistort
dst = cv.undistort(img, mtx, dist, None, newcameramtx)
 
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [47]:
mean_error = 0
for i in range(len(objpoints)):
 imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
 error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
 mean_error += error
 
print( "total error: {}".format(mean_error/len(objpoints)) )

total error: 0.04095711638332795


In [1]:
import numpy as np
import cv2 as cv
import glob

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('./chess_photo3/*.jpg')
print(images)
i = 1
for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (9,6), None)
    #ret, corners = cv.findChessboardCornersSB(gray, (9,6), None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

    print(fname + " OK")
    corners2 = cv.cornerSubPix(gray, corners, (1, 1), (-1, -1), criteria)
    imgpoints.append(corners2)
 
    # Draw and display the corners
    cv.drawChessboardCorners(img, (9,6), corners2, ret)
    cv.imshow('img', img)
    cv.imwrite('./photo3/chess_photo_'+str(i)+'.jpg', img)
    i += 1
    cv.waitKey(100)
 
cv.destroyAllWindows()

['./chess_photo3\\photo (1).jpg', './chess_photo3\\photo (10).jpg', './chess_photo3\\photo (11).jpg', './chess_photo3\\photo (12).jpg', './chess_photo3\\photo (13).jpg', './chess_photo3\\photo (2).jpg', './chess_photo3\\photo (3).jpg', './chess_photo3\\photo (4).jpg', './chess_photo3\\photo (5).jpg', './chess_photo3\\photo (6).jpg', './chess_photo3\\photo (7).jpg', './chess_photo3\\photo (8).jpg', './chess_photo3\\photo (9).jpg']
./chess_photo3\photo (1).jpg OK
./chess_photo3\photo (10).jpg OK


error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\cornersubpix.cpp:58: error: (-215:Assertion failed) count >= 0 in function 'cv::cornerSubPix'


In [47]:
cv.destroyAllWindows()

In [49]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [51]:
images = glob.glob('./chess_photo3/*.jpg')
print(images)
ind = 0
for fname in images:

    ind += 1
    img = cv.imread(fname)
    h, w = img.shape[:2]
    newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))
    # undistort
    dst = cv.undistort(img, mtx, dist, None, newcameramtx)
 
    # crop the image
    x, y, w, h = roi
    dst = dst[y:y+h, x:x+w]
    cv.imwrite('./result3/chess_photo_calibrated_'+str(ind)+'.png', dst)

['./chess_photo5\\photo (1).jpg', './chess_photo5\\photo (10).jpg', './chess_photo5\\photo (11).jpg', './chess_photo5\\photo (12).jpg', './chess_photo5\\photo (2).jpg', './chess_photo5\\photo (3).jpg', './chess_photo5\\photo (4).jpg', './chess_photo5\\photo (6).jpg', './chess_photo5\\photo (7).jpg', './chess_photo5\\photo (8).jpg', './chess_photo5\\photo (9).jpg']


In [53]:
print(ret, mtx, dist, rvecs, tvecs)
np.savez("CameraParams", cameraMatrix=mtx, dist=dist, rvecs=rvecs, tvecs=tvecs)

1.4802260067569142 [[3.50479272e+03 0.00000000e+00 1.55360463e+03]
 [0.00000000e+00 3.51319042e+03 2.09519939e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]] [[ 0.14954522 -0.45017798  0.00216927 -0.00064564  0.41427215]] (array([[0.04698435],
       [0.58314405],
       [1.3305768 ]]), array([[-0.66315479],
       [-0.01766769],
       [ 1.77923079]]), array([[-0.28276485],
       [-0.03430749],
       [ 1.50977637]]), array([[-0.24831912],
       [ 0.27315678],
       [ 1.67469022]]), array([[-0.51443245],
       [ 0.01628988],
       [ 1.46203538]]), array([[-0.72740798],
       [ 0.61789387],
       [ 1.45634594]]), array([[-0.40580754],
       [-0.0451016 ],
       [-1.55039188]]), array([[ 0.08600496],
       [-0.54477372],
       [-1.35115541]]), array([[ 0.32083086],
       [ 0.26469671],
       [-1.5633753 ]]), array([[-0.44003073],
       [-0.13523772],
       [ 3.00637107]]), array([[0.74203646],
       [0.7418499 ],
       [2.86930239]])) (array([[-1.58743628],
      

In [21]:
mean_error = 0
for i in range(len(objpoints)):
 imgpoints2, _ = cv.projectPoints(objpoints[i], rvecs[i], tvecs[i], mtx, dist)
 error = cv.norm(imgpoints[i], imgpoints2, cv.NORM_L2)/len(imgpoints2)
 mean_error += error
 
print( "total error: {}".format(mean_error/len(objpoints)) )

total error: 0.04922471053740006
